### ISSUE TITLE
Got error 'Java heap space' when tried to import AppScale template

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1068]
I have Peer with RH of 8GB. I installed Subutai Management on it, then ssh'ed into management container and executed `sudo subutai import appscale`.
After reaching 512MB it hanged:
![image](https://cloud.githubusercontent.com/assets/4163679/16113552/8dc5cee8-33de-11e6-8593-e3d1225651e6.png)

and in logs following error seen:
>2016-06-16 08:31:25,403 | ERROR | qtp303396474-166 | JAXRSUtils                       | 90 - org.apache.cxf.cxf-rt-frontend-jaxrs - 3.1.0 | Problem with writing the data, class io.subutai.core.kurjun.rest.template.RestTemplateManagerImpl$$Lambda$18/726894810, ContentType: application/octet-stream
2016-06-16 08:31:25,406 | WARN  | qtp303396474-166 | PhaseInterceptorChain            | 91 - org.apache.cxf.cxf-core - 3.1.0 | Interceptor for {http://template.rest.kurjun.core.subutai.io/}RestTemplateManagerImpl has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Java heap space
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:371)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:272)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:118)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:81)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[91:org.apache.cxf.cxf-core:3.1.0]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:94)[127:io.subutai.core.channel.impl:4.0.0.RC14-SNAPSHOT]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:88)[127:io.subutai.core.channel.impl:4.0.0.RC14-SNAPSHOT]
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_91]
	at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_91]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor.handleMessage(AccessControlInterceptor.java:87)[127:io.subutai.core.channel.impl:4.0.0.RC14-SNAPSHOT]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)[40:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_91]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:122)
	at org.apache.commons.io.output.ByteArrayOutputStream.write(ByteArrayOutputStream.java:169)
	at ai.subut.kurjun.repo.RemoteRepositoryBase.getPackageStream(RemoteRepositoryBase.java:110)
	at ai.subut.kurjun.repo.RemoteTemplateRepository.getPackageStream(RemoteTemplateRepository.java:216)
	at ai.subut.kurjun.repo.UnifiedRepositoryImpl.getPackageStream(UnifiedRepositoryImpl.java:110)
	at io.subutai.core.kurjun.impl.TemplateManagerImpl.getTemplateData(TemplateManagerImpl.java:242)
	at Proxy36b72af9_0f69_4254_83b4_db66b38b1572.getTemplateData(Unknown Source)
	at Proxyf627692e_8b49_427d_9604_e24e065d649e.getTemplateData(Unknown Source)
	at io.subutai.core.kurjun.rest.template.RestTemplateManagerImpl.lambda$getTemplate$0(RestTemplateManagerImpl.java:79)[222:io.subutai.core.kurjun.rest:4.0.0.RC14-SNAPSHOT]
	at io.subutai.core.kurjun.rest.template.RestTemplateManagerImpl$$Lambda$18/726894810.write(Unknown Source)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:171)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1375)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:250)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:118)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:81)[90:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[91:org.apache.cxf.cxf-core:3.1.0]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:94)
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:88)
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_91]
	at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_91]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor.handleMessage(AccessControlInterceptor.java:87)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)[91:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)[96:org.apache.cxf.cxf-rt-transports-http:3.1.0]

**Comment by Dilshat** [comment]
This issue is wontfix since we are migrating to Gorjun
