### ISSUE TITLE
Fix ssh key deletion form Hub environment

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1406]
There is an error in ssh key deletion of Hub env.

`2016-11-05 17:30:25,568 | ERROR | ol-50-thread-797 | ConfigureContainerStateHandler   | 182 - io.subutai.core.hubmanager.impl - 4.0.6.SNAPSHOT | Failed to process environment state: 
io.subutai.core.hubmanager.api.exception.HubManagerException: io.subutai.core.hubmanager.api.exception.HubManagerException: io.subutai.common.exception.ActionFailedException: Error resolving peer: Peer not found: 55D9DEED91BC62EC1EE00964C8E7871D399DEF8F
    at io.subutai.core.hubmanager.impl.environment.state.build.ConfigureContainerStateHandler.doHandle(ConfigureContainerStateHandler.java:61)
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.runAs(StateHandler.java:84)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.access$000(StateHandler.java:23)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler$1.run(StateHandler.java:55)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler$1.run(StateHandler.java:51)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_72-internal]
    at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_72-internal]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.handle(StateHandler.java:50)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.HubEnvironmentProcessor.processStateLink(HubEnvironmentProcessor.java:77)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.HubEnvironmentProcessor.processStateLinks(HubEnvironmentProcessor.java:52)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HeartbeatProcessor$2.run(HeartbeatProcessor.java:218)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_72-internal]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_72-internal]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_72-internal]
Caused by: io.subutai.core.hubmanager.api.exception.HubManagerException: io.subutai.common.exception.ActionFailedException: Error resolving peer: Peer not found: 55D9DEED91BC62EC1EE00964C8E7871D399DEF8F
    at io.subutai.core.hubmanager.impl.environment.state.build.ConfigureContainerStateHandler.configureSsh(ConfigureContainerStateHandler.java:163)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.build.ConfigureContainerStateHandler.doHandle(ConfigureContainerStateHandler.java:51)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    ... 13 more
Caused by: io.subutai.common.exception.ActionFailedException: Error resolving peer: Peer not found: 55D9DEED91BC62EC1EE00964C8E7871D399DEF8F
    at io.subutai.core.environment.impl.entity.EnvironmentContainerImpl.getPeer(EnvironmentContainerImpl.java:340)[136:io.subutai.core.environment.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.environment.impl.entity.EnvironmentContainerImpl.getAuthorizedKeys(EnvironmentContainerImpl.java:608)[136:io.subutai.core.environment.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.build.ConfigureContainerStateHandler.getCurrentSshKeys(ConfigureContainerStateHandler.java:219)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.build.ConfigureContainerStateHandler.configureSsh(ConfigureContainerStateHandler.java:84)[182:io.subutai.core.hubmanager.impl:4.0.6.SNAPSHOT]
    ... 14 more`

**Comment by Dilshat** [comment]
Fixed https://github.com/subutai-io/base/pull/1408
