### ISSUE TITLE
Add "force remove" option to RH registration page

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1990]
In case RH send registration request to SS and is gone, and the request is approved, we can not remove it due to error below. This happens b/c resource host after registration sends heartbeat and gets saved to db. If it does not send HB, db record is not created. Remove operation currently searches for db record in addition to registration request record. We need to add option to force remove RH from registrations only without trying to remove it from db.

`2017-08-24 12:27:10,321 | ERROR | tp160807841-2052 | HostRegistrationManagerImpl      | 168 - io.subutai.core.registration.impl - 5.0.1.SNAPSHOT | Error removing registration request
io.subutai.common.peer.HostNotFoundException: Resource host not found by id 41DEBBAE6A29CBB26DE2C4CCB00B83A2340696AA
	at io.subutai.core.localpeer.impl.LocalPeerImpl.getResourceHostById(LocalPeerImpl.java:1082)
	at io.subutai.core.localpeer.impl.LocalPeerImpl.removeResourceHost(LocalPeerImpl.java:1316)
	at Proxyf7df5a7b_7736_46b4_8667_a644b69cd98b.removeResourceHost(Unknown Source)
	at Proxyf7df5a7b_7736_46b4_8667_a644b69cd98b.removeResourceHost(Unknown Source)
	at io.subutai.core.registration.impl.HostRegistrationManagerImpl.removeRequest(HostRegistrationManagerImpl.java:231)
	at Proxy780d461d_eaf0_4e47_82ba_0227ed8a4f50.removeRequest(Unknown Source)
	at Proxy780d461d_eaf0_4e47_82ba_0227ed8a4f50.removeRequest(Unknown Source)
	at Proxydae86156_6a9b_4489_ba70_2c8c807240e1.removeRequest(Unknown Source)
	at io.subutai.core.registration.rest.RegistrationRestServiceImpl.removeRequest(RegistrationRestServiceImpl.java:129)[169:io.subutai.core.registration.rest:5.0.1.SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
	at org.apache.aries.proxy.impl.ProxyHandler$1.invoke(ProxyHandler.java:54)
	at org.apache.aries.proxy.impl.ProxyHandler.invoke(ProxyHandler.java:119)
	at io.subutai.core.registration.rest.$RegistrationRestServiceImpl696502578.removeRequest(Unknown Source)[169:io.subutai.core.registration.rest:5.0.1.SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_111]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)[121:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)[121:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)[120:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)[120:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)[121:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)[121:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[121:org.apache.cxf.cxf-core:3.1.0]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:88)[156:io.subutai.core.channel.impl:5.0.1.SNAPSHOT]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:82)[156:io.subutai.core.channel.impl:5.0.1.SNAPSHOT]
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_111]
	at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_111]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor.handleMessage(AccessControlInterceptor.java:81)[156:io.subutai.core.channel.impl:5.0.1.SNAPSHOT]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[121:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)[121:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)[40:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)[126:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]`

**Comment by Dilshat** [comment]
Implementation will deal with this bug without adding new option. It will handle all cases.
Also now in case RH has environment containers, it is prohibited to delete it without first destroying them or the entire environment.
