### ISSUE TITLE
 Environment creation via HUB broken with NPE

### ISSUE THREAD

**Issue by absidish** [subutai-io/base#2103]
Sometimes getting ERROR: 

``` 2017-11-02 10:39:24,131 | ERROR | ool-564-thread-1 | EnvironmentUserHelper            | 190 - io.subutai.core.hubmanager.impl - 6.1.4.SNAPSHOT | Error to create user: 
java.lang.IllegalArgumentException: User with name 280dcda67a67d071970ff838d0331c33c0c04710 already exists
    at io.subutai.core.identity.impl.IdentityManagerImpl.createUser(IdentityManagerImpl.java:1290)
    at Proxy11d4dd63_f56d_44fd_a94d_59f08fc10b89.createUser(Unknown Source)
    at Proxy11d4dd63_f56d_44fd_a94d_59f08fc10b89.createUser(Unknown Source)
    at Proxyc2358059_7d8e_4a1e_894e_21405c0455de.createUser(Unknown Source)
    at io.subutai.core.hubmanager.impl.util.EnvironmentUserHelper.createUser(EnvironmentUserHelper.java:177)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.util.EnvironmentUserHelper.handleEnvironmentOwnerCreation(EnvironmentUserHelper.java:135)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.build.ExchangeInfoStateHandler.doHandle(ExchangeInfoStateHandler.java:35)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.runAs(StateHandler.java:103)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.access$000(StateHandler.java:25)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler$1.run(StateHandler.java:60)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler$1.run(StateHandler.java:56)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_131]
    at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_131]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.handle(StateHandler.java:55)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HubEnvironmentProcessor.processStateLink(HubEnvironmentProcessor.java:105)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HubEnvironmentProcessor.access$000(HubEnvironmentProcessor.java:20)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HubEnvironmentProcessor$1.call(HubEnvironmentProcessor.java:61)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_131]
    at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
2017-11-02 10:39:24,132 | ERROR | ool-564-thread-1 | ExchangeInfoStateHandler         | 190 - io.subutai.core.hubmanager.impl - 6.1.4.SNAPSHOT | Failed to process environment state: 
io.subutai.core.hubmanager.api.exception.HubManagerException: java.lang.NullPointerException
    at io.subutai.core.hubmanager.impl.environment.state.build.ExchangeInfoStateHandler.doHandle(ExchangeInfoStateHandler.java:63)
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.runAs(StateHandler.java:103)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.access$000(StateHandler.java:25)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler$1.run(StateHandler.java:60)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler$1.run(StateHandler.java:56)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_131]
    at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_131]
    at io.subutai.core.hubmanager.impl.environment.state.StateHandler.handle(StateHandler.java:55)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HubEnvironmentProcessor.processStateLink(HubEnvironmentProcessor.java:105)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HubEnvironmentProcessor.access$000(HubEnvironmentProcessor.java:20)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at io.subutai.core.hubmanager.impl.processor.HubEnvironmentProcessor$1.call(HubEnvironmentProcessor.java:61)[190:io.subutai.core.hubmanager.impl:6.1.4.SNAPSHOT]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_131]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_131]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_131]
    at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
Caused by: java.lang.NullPointerException
    at io.subutai.core.hubmanager.impl.environment.state.build.ExchangeInfoStateHandler.doHandle(ExchangeInfoStateHandler.java:36)
    ... 16 more```

**Comment by Dilshat** [comment]
In case user already exists, *EnvironmentUserHelper.handleEnvironmentOwnerCreation* should return it instead of rethrowing exception from createUser method
