### ISSUE TITLE
Hello! I love this software.

### ISSUE THREAD

**Issue by Gr1dd** [subutai-io/base#2137]
I think you guys are on to something really good.

I would love to help development, or if there is anything you need at all feel free to let me know.

I wrote a ubuntu install script if you guys are interested, but the java_env and path variable could be better automated. I'll PR that for you if you want it. Basically you just hafto wget the install script and it takes care of the rest for a ubuntu instance.

I do have one slight issue though, I registered to the hub through github login, and well... When I try and register my nodes to the hub the login box spins for a moment and reverts. I'm using the latest chrome.

I'll try and dig in and see if there's anything obvious. Maybe your auth server is down? No idea :)

Take care!

**Comment by Gr1dd** [comment]
```server:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_151]
Caused by: java.lang.NullPointerException
	at io.subutai.core.hubmanager.impl.HubManagerImpl.getHubConfiguration(HubManagerImpl.java:609)
	at io.subutai.core.hubmanager.impl.HubManagerImpl.isRegisteredWithHub(HubManagerImpl.java:545)
	at Proxy1acc33a4_2822_410d_81d5_e82b4a6693d9.isRegisteredWithHub(Unknown Source)
	at Proxy1acc33a4_2822_410d_81d5_e82b4a6693d9.isRegisteredWithHub(Unknown Source)
	at Proxyd83d629b_97ee_4abd_a7a3_69a32e9332d2.isRegisteredWithHub(Unknown Source)
	at io.subutai.core.hubmanager.rest.RestServiceImpl.getRegistrationState(RestServiceImpl.java:121)[209:io.subutai.core.hubmanager.rest:6.2.1.SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_151]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)[108:org.apache.cxf.cxf-core:3.1.0]
	... 48 more
2017-11-22 17:51:55,614 | ERROR | tp328063874-1477 | tractFaultChainInitiatorObserver | 108 - org.apache.cxf.cxf-core - 3.1.0 | Error occurred during error handling, give up!
org.apache.cxf.interceptor.Fault
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:163)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:129)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)[107:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)[107:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[108:org.apache.cxf.cxf-core:3.1.0]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:88)[143:io.subutai.core.channel.impl:6.2.1.SNAPSHOT]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:82)[143:io.subutai.core.channel.impl:6.2.1.SNAPSHOT]
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_151]
	at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_151]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor.handleMessage(AccessControlInterceptor.java:81)[143:io.subutai.core.channel.impl:6.2.1.SNAPSHOT]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:217)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)[40:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_151]
Caused by: java.lang.NullPointerException
	at io.subutai.core.hubmanager.impl.HubManagerImpl.getHubConfiguration(HubManagerImpl.java:609)
	at io.subutai.core.hubmanager.impl.HubManagerImpl.isRegisteredWithHub(HubManagerImpl.java:545)
	at Proxy1acc33a4_2822_410d_81d5_e82b4a6693d9.isRegisteredWithHub(Unknown Source)
	at Proxy1acc33a4_2822_410d_81d5_e82b4a6693d9.isRegisteredWithHub(Unknown Source)
	at Proxyd83d629b_97ee_4abd_a7a3_69a32e9332d2.isRegisteredWithHub(Unknown Source)
	at io.subutai.core.hubmanager.rest.RestServiceImpl.getRegistrationState(RestServiceImpl.java:121)[209:io.subutai.core.hubmanager.rest:6.2.1.SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_151]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)[108:org.apache.cxf.cxf-core:3.1.0]
	... 48 more```

**Comment by Gr1dd** [comment]
New release won't compile .deb. D:

**Comment by Dilshat** [comment]
@Gr1dd Hello!
We are glad you joined us.
We are looking into the issue you reported above
Can you give more info about compilation problems you are experiencing, please?
Thanks

**Comment by Gr1dd** [comment]
```
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:11 min
[INFO] Finished at: 2017-11-23T04:41:08+00:00
[INFO] Final Memory: 180M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project subutai: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :subutai
``` 
All were success, but I think it -rf'd the .deb

command: sudo mvn install -P deb

**Comment by Dilshat** [comment]
We keep master usually the same as release

**Comment by Gr1dd** [comment]
Cool cool. I started looking for software like this in this process:
I thought of ethereum, it only allows for the golem project to run blender files in the evm. (Rendering)
Then I was thinking, why not a decentralized docker blockchain that pays for performance and processing time based on some type of equation.

I started on the task of trying to get dragonchain working. It kind of worked........... BUT! It needed access control on the user-end through aes keys to keep the fraud out of the equation. These are nothing like PGP keys..... Although you could encrypt with CFB cipher and allow for any-length key and pad the current local user key for basically inputting anything as a key.
(atleast... that's as far as I got besides writing a few json files to send level 1 authenticated transactions to the blockchain node)
Have you thought of running a blockchain or something of that sort and doing like a 100% ICO to yourself, then transferring your goodwill to the node (that you would generate a unique blockchain address for each account per say) and sending a transaction calculated on processing time*cores*ram*space kind of equation to the node based on that account, then allowing exchanges like poloniex, gdax, bitfinex, kraken, and cex.io trade your goodwill at real market value running your linked node? 

It's the millenial appeal these days really. I think it could go really really really far and reap the benefits of popularity in those user markets.


Anyway, I ditched the .deb package. I feel like this is why I was so hyped on getting a .deb for portability unless you could make this globally available through apt somehow. 
On ubuntu 16.04 LTS.... My P2P information is not displayed, even after disabling the applock, and installing all the debian packages on ubuntu. I thought this is maybe why I couldn't link to the hub.

Thanks :)

**Comment by Gr1dd** [comment]
getting some errors here:
```
karaf@root>[FelixStartLevel] INFO org.ops4j.pax.web.service.internal.Activator - EventAdmin support is not available, no servlet events will be posted!
[FelixStartLevel] INFO org.ops4j.pax.web.service.internal.Activator - LogService support enabled, log events will be created.
[FelixStartLevel] INFO org.ops4j.pax.web.service.internal.Activator - Pax Web started
2017-11-23 11:02:24,991 | DEBUG | FelixStartLevel  | jetty                            | 204 - io.subutai.core.http.context.jetty - 6.2.2.SNAPSHOT |  | BundleEvent RESOLVED - io.subutai.core.http.context.jetty
2017-11-23 11:02:24,993 | DEBUG | FelixStartLevel  | jetty                            | 204 - io.subutai.core.http.context.jetty - 6.2.2.SNAPSHOT |  | BundleEvent RESOLVED - io.subutai.core.http.context.jetty
[FelixStartLevel] INFO org.apache.aries.blueprint.container.BlueprintContainerImpl - Bundle org.apache.aries.transaction.blueprint/1.0.2 is waiting for dependencies [(objectClass=javax.transaction.TransactionManager)]
[pool-5-thread-1] INFO org.eclipse.jetty.server.Server - jetty-8.1.17.v20150415
[FelixStartLevel] INFO org.apache.sshd.common.util.SecurityUtils - Trying to register BouncyCastle as a JCE provider
[pool-5-thread-1] INFO org.eclipse.jetty.util.ssl.SslContextFactory - Enabled Protocols [SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2] of [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
[pool-5-thread-1] INFO org.eclipse.jetty.server.AbstractConnector - Started SslSelectChannelConnector@0.0.0.0:8443
[pool-5-thread-1] INFO org.eclipse.jetty.util.ssl.SslContextFactory - Enabled Protocols [SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2] of [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
[pool-5-thread-1] INFO org.eclipse.jetty.server.AbstractConnector - Started SslSelectChannelConnector@0.0.0.0:8444
[pool-5-thread-1] INFO org.ops4j.pax.web.service.jetty.internal.JettyServerImpl - Pax Web available at [0.0.0.0]:[8443]
[pool-5-thread-1] INFO org.ops4j.pax.web.service.jetty.internal.JettyServerImpl - Pax Web available at [0.0.0.0]:[8444]
[pool-5-thread-1] INFO org.ops4j.pax.web.service.jetty.internal.JettyServerImpl - Pax Web available at [0.0.0.0]:[8080]
[pool-5-thread-1] INFO org.eclipse.jetty.server.AbstractConnector - Started NIOSocketConnectorWrapper@0.0.0.0:8080
[FelixStartLevel] INFO org.apache.sshd.common.util.SecurityUtils - Registration succeeded
```

But I set my java environment in a screen like this:

```
mvn clean install
cd ../../
echo "CD back to home directory, then last shot to the bin executable, setting permissions, unzipping tar.gz..."
cd base/management/server/server-karaf/target
sudo tar xzvf *.tar.gz
sudo chmod 777 -R ../../../../../
sudo chmod 777 -R /data
cd base/management/server/server-karaf/target/subutai*/bin
cd subutai*/bin
echo "We will now put you into screen, to detach ctrl+a then d or to reattach: screen -x"
sleep 5s
screen -d -m bash -c "export JAVA_HOME=/usr/lib/jvm/java-8-oracle; export PATH=$JAVA_HOME/bin:$PATH; ./karaf"
echo "Done, please navigate to https://localhost:8443 with username: admin and password: secret to complete setup!"
```

It's the only way for me to load the environment, in sudo (export doesnt work in sudo) detached on google cloud so the session doesn't end....

**Comment by Gr1dd** [comment]
Nevermind! It loaded.... Just took awhile. :)

**Comment by Gr1dd** [comment]
```mvn clean install
cd ../../
echo "CD back to home directory, then last shot to the bin executable, setting permissions, unzipping tar.gz..."
cd base/management/server/server-karaf/target
sudo tar xzvf *.tar.gz
sudo chmod 777 -R ../../../../../
sudo chmod 777 -R /data
cd base/management/server/server-karaf/target/subutai*/bin
cd subutai*/bin
echo "We will now put you into screen, to detach ctrl+a then d or to reattach: screen -x"
sleep 5s
screen -d -m bash -c "export JAVA_HOME=/usr/lib/jvm/java-8-oracle; export PATH=$JAVA_HOME/bin:$PATH; ./karaf"
echo "Done, please navigate to https://localhost:8443 with username: admin and password: secret to complete setup!"
```
Is how I'm running on google cloud right now. 

I'm concerned about the chmod, because, I can't export my settings to sudo in a screen (export doesnt exist in sudo) as well, In this script. (I had a previous one that exported to the profile, but that thing is very sensitive -> /etc/profile) this seems easier.

I'd likely write a start.sh and pull this install script (since, it's compatible with ubuntu afaik and debian)

In start.sh drop a one-liner:
```
screen -d -m bash -c "export JAVA_HOME=/usr/lib/jvm/java-8-oracle; export 
``` Don't use tilde `

**Comment by Gr1dd** [comment]
So far my install is back to compiling from github, releases have no .git...
https://raw.githubusercontent.com/Gr1dd/subut.ai/master/debinstall.sh

Also ruins ssh for some reason on my cloud instance.

**Comment by Gr1dd** [comment]
```
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:11 min
[INFO] Finished at: 2017-11-23T04:41:08+00:00
[INFO] Final Memory: 180M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project subutai: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :subutai
```

Releases still have this error. I would love to make a release, I'm going to try and fix this on a separate git repo
