### ISSUE TITLE
For background jobs, identityManager.getActiveUser should return some internal system user

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#851]
Currently we have problems when background job running regularly tries to get Active User.
We need to add some internal limited user, which will be used for this purpose.

Logs:

`2016-05-09 07:49:45,561 | ERROR | pool-33-thread-1 | TrackerImpl                      | 195 - io.subutai.core.tracker.impl - 4.0.0.RC11 | Error in saveTrackerOperation
java.lang.NullPointerException
    at io.subutai.core.tracker.impl.TrackerImpl.saveTrackerOperation(TrackerImpl.java:88)[195:io.subutai.core.tracker.impl:4.0.0.RC11]
    at io.subutai.core.tracker.impl.TrackerImpl.createTrackerOperation(TrackerImpl.java:114)[195:io.subutai.core.tracker.impl:4.0.0.RC11]
    at Proxy23f3f437_f16d_4324_b0b2_28c106377092.createTrackerOperation(Unknown Source)[:]
    at Proxyb8878fb8_4ccc_4a70_ba02_83f9a81c35e6.createTrackerOperation(Unknown Source)[:]
    at io.subutai.core.environment.impl.EnvironmentManagerImpl.resetP2PSecretKey(EnvironmentManagerImpl.java:797)[117:io.subutai.core.environment.impl:4.0.0.RC11]
    at io.subutai.core.environment.impl.EnvironmentManagerImpl.resetP2Pkey(EnvironmentManagerImpl.java:1808)[117:io.subutai.core.environment.impl:4.0.0.RC11]
    at io.subutai.core.environment.impl.EnvironmentManagerImpl.access$300(EnvironmentManagerImpl.java:101)[117:io.subutai.core.environment.impl:4.0.0.RC11]
    at io.subutai.core.environment.impl.EnvironmentManagerImpl$BackgroundTasksRunner.run(EnvironmentManagerImpl.java:1786)[117:io.subutai.core.environment.impl:4.0.0.RC11]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_51]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_51]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_51]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_51]
2016-05-09 07:49:45,613 | INFO  | pool-1-thread-1  | HubLoggerProc`

**Comment by nk-the-crazy** [comment]
Added JAAS authentication for Background jobs (resetp2p will run as System User)
